name: Branch Protection

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/branch-protection.yml'

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Branch Protection
        uses: softprops/branch-protection-action@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce_admins: false
          required_status_checks: |
            {
              "strict": true,
              "contexts": ["test"]
            }
          required_pull_request_reviews: |
            {
              "required_approving_review_count": 1,
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false
            }
          restrictions: |
            {
              "users": [],
              "teams": [],
              "apps": []
            } 